"""initial commit

Revision ID: d750e8c6e677
Revises: e63620a1dd6c
Create Date: 2025-01-03 21:38:40.940987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd750e8c6e677'
down_revision: Union[str, None] = 'e63620a1dd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('assets', 'asset_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assets', 'asset_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('assets', 'asset_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    # ### end Alembic commands ###
